# -*- coding: utf-8 -*-
"""app2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AQKz2tT9t9LPaXgz9sPJmfouw2EPcsOA
"""

import streamlit as st
import numpy as np
import pickle

with open('model.pkl', 'rb') as f:
    model = pickle.load(f)

st.title('💵 Salary Prediction App')

AGE = st.slider("Select Age",max_value=60,min_value=18,step=1)
GENDER =st.selectbox("Select Gender",["Male","Female"])
if GENDER == "Male":
    GENDER = 1
else:
    GENDER = 0
ED = st.selectbox("Select Education Level",["Bachelors","Masters","Phd"])
if ED == "Bachelors":
    ED = 0
elif ED == "Masters":
    ED = 1
else:
    ED = 2
YR = st.slider("Select Years of Experience",max_value=30,min_value=0,step=1)

if st.button('Predict'):
  data = np.array([[AGE,GENDER,ED,YR]])
  prediction = model.predict(data)
  st.success(f'Predicted Salary: ₹{prediction[0]:,.2f}')


